export class CommonConstants {

  static readonly BASE_URL: string = 'https://devapp.ss-tjd.com'

  // global data key
  static readonly G_STORE: string = 'GreenTreasureStore';

  static readonly TOKEN: string = 'TOKEN'

  static readonly NULL_TOKEN: string = ''

  static readonly TOKEN_INVALIDATION : number = 401

  static readonly CODE_SUCCESS : number = 200

  static readonly TOKEN_INVALIDATION_MSG : string = 'token过期，请重新登录'

  static readonly REQUEST_ERROR : string = '请求失败'

  static readonly LOGIN_PAGE_URL : string = '/pages/Login/Index'

}